export const EVENT_TYPES = {
  WEDDING: "wedding",
  BIRTHDAY: "birthday",
  ANNIVERSARY: "anniversary",
  GRADUATION: "graduation",
  CORPORATE: "corporate",
} as const;

export const EVENT_TYPES_ES = {
  BODA: "boda",
  CUMPLEANOS: "cumpleanos",
  ANIVERSARIO: "aniversario",
  GRADUACION: "graduacion",
  CORPORATIVO: "corporativo",
} as const;

export const EVENT_TYPE_MAP: Record<string, string> = {
  [EVENT_TYPES_ES.BODA]: EVENT_TYPES.WEDDING,
  [EVENT_TYPES_ES.CUMPLEANOS]: EVENT_TYPES.BIRTHDAY,
  [EVENT_TYPES_ES.ANIVERSARIO]: EVENT_TYPES.ANNIVERSARY,
  [EVENT_TYPES_ES.GRADUACION]: EVENT_TYPES.GRADUATION,
  [EVENT_TYPES_ES.CORPORATIVO]: EVENT_TYPES.CORPORATE,
  [EVENT_TYPES.WEDDING]: EVENT_TYPES.WEDDING,
  [EVENT_TYPES.BIRTHDAY]: EVENT_TYPES.BIRTHDAY,
  [EVENT_TYPES.ANNIVERSARY]: EVENT_TYPES.ANNIVERSARY,
  [EVENT_TYPES.GRADUATION]: EVENT_TYPES.GRADUATION,
  [EVENT_TYPES.CORPORATE]: EVENT_TYPES.CORPORATE,
} as const;

export type EventType = typeof EVENT_TYPES[keyof typeof EVENT_TYPES];
export type EventTypeEs = typeof EVENT_TYPES_ES[keyof typeof EVENT_TYPES_ES];
